version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
      	    - POSTGRES_PASSWORD=postgres_password
    api:
        depends_on:
            - postgres
        restart: always    
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
             - "3000:3000"    
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DATABASE=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432